components
js-tasks-ru/vue-20210628_ratatujef pull request #5
Opened 2021-08-19 13:33 UTC by ratatujef

2021-08-19 13:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-22 09:14 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-22 18:40 UTC, ShGKme requested changes
В 01-CounterButtonComponent требуется заменить проверки на явную установку значения по умолчанию. Остальные задачи приняты

2021-08-22 18:40 UTC, ShGKme commented on 02-components/02-MeetupDescription/MeetupDescription.js
> +  template: `<p v-if='description' class="meetup-description">{{description}}</p>`,
В текстовой интерполяции принято добавлять пробелы `{{ description }}`

2021-08-22 18:40 UTC, ShGKme commented on 02-components/04-MeetupInfo/MeetupInfo.js
> +        <time :datetime="new Date(date).toISOString().substr(0, 10)">{{meetupDate}}</time>
Атрибуты `datetime` получился сложным. Лучше такие вычисления выносить в вычисляемые свойства, чтобы не усложнять шаблон логикой.

2021-08-22 18:40 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  >{{count||0}}</button>`,
Значение по умолчанию должно описываться в опции `default` входного параметра. Это явно описывает значение по умолчанию, и избавляет от последующих проверок по всему компоненту

2021-08-22 18:40 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Этому компоненту не нужно локальное состояние, и оно не используется в этом решении.

2021-08-23 16:57 UTC, ratatujef commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
done

2021-08-23 16:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-08-23 20:04 UTC, ShGKme approved these changes
Все задачи приняты

2021-08-23 20:04 UTC, ShGKme commented on 02-components/02-MeetupDescription/MeetupDescription.js
> +  template: `<p v-if='description' class="meetup-description">{{ description }}</p>`,
Забыл добавить, что такие `v-if='description'` обычно не нужны. Если данных для компонента нет, и ничего не требуется рендерить, то обычно родитель сам не рендерит этот компонент.

2021-08-23 20:06 UTC, merged